name: pbdl
description: A starting point for Dart libraries or applications.
version: 2.1.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.4.2
  azblob: ^2.3.0
  collection: ^1.18.0
  get_it: ^7.6.0
  hex: ^0.2.0
  http2: ^2.0.1
  json_annotation: ^4.6.0
  meta: ^1.12.0
  path: ^1.8.3
  quick_log: ^5.2.1
  recase: ^4.1.0
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  pedantic: ^1.11.1
  test: ^1.21.4
